# -*- coding: utf-8 -*-
"""Grouping in Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tK07dX34L7ouoH8NKaKMog0LFHKQqcSa
"""

# Grouping in Pandas

# import pandas as pd

# empDF = pd.DataFrame({
#     "empName": ["Gangaram", "Changaram", "Pangaram", "Dangaram", "Lambaram", "Mangiram", "Rajaram"],
#     "empAge": [32,52,34,32,52,34,22],
#     "empSalary": [20000,30000,50000,50000,74000,45000,12000]
# })
# print(empDF)
# groupedData1 = empDF.groupby("empAge").sum()
# groupedData2 = empDF.groupby("empAge")["empSalary"].sum()
# print(groupedData1)
# print(groupedData2)

# avgEmpSal = empDF['empSalary'].mean()
# stdEmpSal = empDF['empSalary'].std()
# minEmpSal = empDF['empSalary'].min()
# maxEmpSal = empDF['empSalary'].max()
# countOfEmpSal = empDF['empSalary'].count()
# sumEmpSal = empDF['empSalary'].sum()

# print(avgEmpSal)
# print(stdEmpSal)
# print(minEmpSal)
# print(maxEmpSal)
# print(countOfEmpSal)
# print(sumEmpSal)

# Bakeri DataFrame Grouping

# bakDF = pd.DataFrame({
#     "prod": ["Cake", "Cookies", "Pastries", "Biscuits", "Muffins", "Donuts", "Doracake"],
#     "pricing": [450, 120, 120, 60, 25, 20, 50],
#     "SalesDemand": [50, 100, 80, 62, 75, 85, 93],
#     "TimeStamp": ["01/02/2025", "01/02/2025", "01/03/2025", "01/02/2025", "01/03/2025", "01/03/2025", "01/02/2025"]
# })
# print(bakDF)

# grpBakData = bakDF.groupby("TimeStamp")["SalesDemand"].sum()
# grpBakData = bakDF.groupby("TimeStamp")["pricing"].sum()
# bakDF["tPrice"] = bakDF["pricing"]*bakDF["SalesDemand"]
# bakDF
# grpBakData = bakDF.groupby("TimeStamp")[["tPrice", "SalesDemand"]].sum()
# grpBakData

# Grouping Attributes -

import pandas as pd

# store_df = pd.DataFrame({
#     'storeType': ['Z', 'Y', 'X', 'Z', 'Y', 'Z', 'Y'],
#     'sales': [1200, 450, 120, 85, 652, 324, 210],
#     'month': [1,1,2,3,1,1,2]
# })

# print(store_df)
# sort | as_index | by
# sales_summary = store_df.groupby(by='storeType', sort=False, as_index=True)['sales'].sum()
# print(sales_summary)
# sales_summary = store_df.groupby(by='storeType', sort=True, as_index=False)['sales'].sum()
# print(sales_summary)
# sales_summary = store_df.groupby(by=['storeType', 'month'])['sales'].sum()
# print(store_df)
# print(sales_summary)

# df = pd.DataFrame({
#     'category': ['A', 'B', None, 'D', 'A', 'B', 'D'],
#     'sub-cat': ['a', 'b', None, 'd', 'a', None, 'd'],
#     'stock_value': [10,20,None,30,68,None,12]
# })

# print(df)

# grouping = df.groupby(by=['category', 'sub-cat'], sort=False, as_index=False, dropna=False)['stock_value'].sum()
# print(grouping)

# .agg() or .aggregate()

# empDF = pd.DataFrame({
#     'empDept': ['HR', 'IT', 'HR', 'Finance', 'IT', 'Finance', 'WFM'],
#     'empSalary': ['15k', '20k', '68k', '41k', '36k', '24k', '85k'],
#     'incentive': ['2k', '1.5k', '2.1k', '3.6k', '1.5k', '7.2k', '.5k']
# })

# print(empDF)

# newDF = empDF.groupby(by='empDept', as_index=False).agg({
#     'empSalary': ['sum', 'count'],
#     'incentive': ['sum', 'min']
# })
# newDF

# newDF = empDF.groupby(by='empDept', as_index=False).agg(
#     TotalSalary=('empSalary', 'sum'),
#     TotalI=('incentive', 'sum'),
#     AvSal=('empSalary', 'mean')
# )
# newDF

df = pd.DataFrame({
    'team': ['Ind', 'Ind', 'SA', 'SA', 'NZ'],
    'score': [251, 210, 159, 325, 326]
})

newDf = df.groupby('team')['score'].transform(lambda y: y - y.mean())
print("pre df : ", newDf)
newDf = df.groupby('team').filter(lambda y: y['score'].sum() >= 462)
print("curr df : ",newDf)

