# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L1zf2sYpboo3X7Cf5JCdyT4DofH3wSX4
"""

import pandas as pd

demoData = {
    "userName": ["Bhavya", "Rahul", "Girdhari", "Dhanshyan"],
    "subsModel": ["Premium", "Standard", "Premium", "Basic"],
    "subsPrice": [1999, None, 1799, None],
    "subsMonth": [12,None,2,7]
}

df = pd.DataFrame(demoData)
print(df)

# .drop() - used to remove a particular column (inplace --> True --> Original DF changes  |  inplace --> false --> New | Copied DF)
# newDf = df.drop(columns='subsMonth', inplace=False)
# df.drop(columns='subsMonth', inplace=True)
# print(newDf)
# print(df)




# Handling Missing and Null Values -

# .isnull() - used to find the missing | null values from a DF | it will return a boolean array or DF
# nullCheck = df.isnull().sum() # it will provide a count or a sum or each column's null or missing values
# nullCheck = df.isnull()
# print(nullCheck)

# .dropna() - used to remove data on the basis of axis --> o - rows | 1 - columns
# df.dropna(inplace=True)
# df.dropna(axis=1, inplace=True)
# print(df)

# .fillna() - used to fill a particular row's null value or column's missing value
# df['subsPrice'] = df['subsPrice'].fillna(df['subsPrice'].mean())
# df['subsMonth'] = df['subsMonth'].fillna(df['subsMonth'].mean())
# print(df)

