# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L1zf2sYpboo3X7Cf5JCdyT4DofH3wSX4
"""

import numpy as np
import pandas as pd

dataset = pd.read_csv("MOCK_DATA.csv")
print(dataset)

dataset['discount'] = dataset['Prod_Price'] * .1
print(dataset)

dataset.insert(4, 'final_price', dataset['Prod_Price'] - dataset['discount'])
print(dataset)

print(dataset)

dataset.loc[0, 'Prod_Cat'] = "Mens Jeans"
print(dataset)

# - Create a NumPy array containing all product prices.
# - Find the maximum, minimum, and average price from the array.
# - Create a NumPy array of all prices and apply a 10% discount to each item.
# - Using NumPy, find how many products have a price greater than $20.
# - Create a NumPy array of 1s having the same length as the number of products.
# - Multiply this array element-wise by product prices (simulate a “buy 1 each” total).
# - Sort all prices in ascending order using NumPy.
# - Reshape the NumPy array of prices into a 5×6 matrix.
# - Generate random integers (1–10) representing stock counts for each product and multiply them with -
#   prices to calculate total stock value.
# - Find standard deviation and variance of all product prices using NumPy.





# - Read the dataset into a Pandas DataFrame and display its first and last 5 records.
# - Display all product names from the “Food - Frozen Foods” category.
# - Show only Prod_Name and Prod_Price columns.
# - Find total number of unique Prod_Cat categories.
# - Retrieve all rows where price is less than $10.
# - Find all products that belong to the Kitchen category.
# - Count how many products belong to the Food main category (any subcategory starting with “Food -”).
# - Filter products whose names contain the word "Mug".
# - Display only products whose Prod_Sub contains “Pasta”.
# - Find all products priced between $10 and $40 (inclusive).

